- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
    gate:
      queue: core
      jobs:
        - linters:
            vars:
              linters:
                - coala
